name: ExpressLRS Configurator
description: 'App to build & flash ExpressLRS firmware.'
website: 'https://github.com/ExpressLRS/ExpressLRS-Configurator'
repository: 'https://github.com/ExpressLRS/ExpressLRS-Configurator'
keywords:
  - firmware
  - embedded
  - drones
  - radio
  - utilities
category: Utilities
license: GPLv3
youtube_video_url: 'https://www.youtube.com/watch?v=wBUamLm51XQ'
